### ISSUE TITLE
404 Page

### ISSUE THREAD

**Issue by myka-p** [AshlavaDev/cpnt260-final-project#3]
# Context
Create a 404 page for the Final Assignment.

# Task List
- [ ] Find an image - if using a background or hero
- [ ] Should not have vertical or horizontal scroll
- [ ] Should be mobile compatible
- [ ] Should have the 
  - [ ] header
  - [ ] nav
  - [ ] footer
  -  [ ] or the nav can be not included, have a CTA to ‘go back to homepage’ instead
  - [ ] a short phrase (Sorry…)
  
# Definition of Done
When every component has been incorporated, and the webpage is deemed presentable.
