### ISSUE TITLE
Team/ Contact page

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/cpnt260-final-project#4]
# Context

Create a page showcasing the team

# Task List

- [ ] Organize cards into a small gallery
- [ ] Apply style to fit whole website
- [ ] Add other features such as contact form and map
- [ ] Ensure page meets accessibility criteria

# Definition of Done

Page is formatted, no missing components, nothing breaks

**Comment by AshlavaDev** [comment]
Edited with task changes
