### ISSUE TITLE
Contact Form

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/cpnt260-final-project#5]
# Context

A form that can be used to send the team a message

# Task List

- [ ] Create html for form
- [ ] Link to Formspree or other service
- [ ] Apply the html to page
- [ ] Style the form appropriately

# Definition of Done

Form works and fits into the web page
