### ISSUE TITLE
Create bio cards

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/cpnt260-final-project#6]
# Context

Cards for each member of the web dev team, with a picture, name, socials, and a tagline

# Task List

- [ ] Create a card design to fit into page
- [ ] Each team member uses relevant info and card is filled out
- [ ] Place card into page
- [ ] Do any style changes to ensure good fit for website

# Definition of Done

The cards contain an image, a name, a tagline, and any links to social media. They have a final style for the page.
