### ISSUE TITLE
Gallery Card

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/cpnt260-final-project#7]
# Context

Individual clickable cards for the gallery

# Task List

- [ ] Create basic framework for card
- [ ] Style card to fit website
- [ ] Make the whole card a link

# Definition of Done

Card has a layout and is functional as a link
