### ISSUE TITLE
Moodboard

### ISSUE THREAD

**Issue by AshlavaDev** [AshlavaDev/cpnt260-final-project#9]
# Context

Establish a resource of all inspiration for design that everyone can contribute to

# Task List

- [ ] Start a shared space with a basic layout
- [ ] Place any interesting colour palettes
- [ ] Place screenshots of inspiring websites
- [ ] Place any other inspiring media such as cool pictures

# Definition of Done

A moodboard with different design elements is finished that can be referenced in build stage
